/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiSelectField: typeof import('./src/components/fields/ApiSelectField.vue')['default']
    BaseModal: typeof import('./src/@core/components/modals/BaseModal.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    CategoryManySelectField: typeof import('./src/components/fields/CategoryManySelectField.vue')['default']
    CategorySingleSelectField: typeof import('./src/components/fields/CategorySingleSelectField.vue')['default']
    CompactDatePicker: typeof import('./src/components/common/CompactDatePicker.vue')['default']
    ConditionStatistic: typeof import('./src/components/areas/ConditionStatistic.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    NumberField: typeof import('./src/components/fields/NumberField.vue')['default']
    PhotoPreview: typeof import('./src/components/common/PhotoPreview.vue')['default']
    PromptModal: typeof import('./src/@core/components/modals/PromptModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UploadPhotoAWS: typeof import('./src/components/common/UploadPhotoAWS.vue')['default']
    UploadPhotosMany: typeof import('./src/components/common/UploadPhotosMany.vue')['default']
    YandexMapTrees: typeof import('./src/components/common/YandexMapTrees.vue')['default']
  }
}
