# Generated by Django 4.2.13 on 2025-10-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_checkupphotoannotation_is_tree_finded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkupphotoannotation",
            name="breed",
            field=models.CharField(
                choices=[
                    ("unknown", "Не определено"),
                    ("oak", "Дуб"),
                    ("ash", "Ясень"),
                    ("poplar", "Тополь"),
                    ("pine", "Сосна"),
                    ("birch", "Берёза"),
                    ("elm", "Вяз"),
                    ("maple", "Клён"),
                    ("spruce", "Ель"),
                    ("catalpa", "Катальпа"),
                    ("willow", "Ива"),
                    ("linden", "Липа"),
                    ("acacia", "Акация"),
                    ("aspen", "Осина"),
                    ("chestnut", "Каштан"),
                    ("apple", "Яблоня"),
                    ("cherry", "Вишня"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
